apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ohfr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ohfr
    app.kubernetes.io/part-of: byoc-app-dpdo
  name: ohfr
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ohfr
status:
  loadBalancer: {}
